"use client"

import { TrendingUp } from "lucide-react"
import { Area, AreaChart, CartesianGrid, XAxis, ResponsiveContainer, Tooltip } from "recharts"

interface ChartDataPoint {
    month: string;
    revenue: number;
}

interface CumulativeRevenueChartProps {
    data?: ChartDataPoint[];
    totalRevenue: number;
    trend?: number | null;
}

export function CumulativeRevenueChart({ data = [], totalRevenue, trend }: CumulativeRevenueChartProps) {
    const defaultData = [
        { month: "Day 1", revenue: 0 },
        { month: "Today", revenue: 0 },
    ];

    // Use passed data or fallback to avoid crash, but prefer passed data
    const chartData = data.length > 0 ? data : defaultData;

    return (
        <div className="p-6 rounded-xl ">
            <div className="flex justify-between items-end mb-6">
                <div>
                    <h4 className="text-sm font-semibold text-gray-500 uppercase tracking-wide">
                        Cumulative Revenue
                    </h4>
                    <p className="text-3xl font-medium text-gray-900 mt-1 font-geist-mono">
                        {new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', minimumFractionDigits: 0 }).format(totalRevenue)}
                    </p>
                    <div className="text-gray-400 text-xs mt-1">
                        Additional revenue generated by Narrativee
                    </div>
                </div>

                {trend !== undefined && trend !== null && trend !== 0 && (
                    <div className={`flex items-center gap-1 text-sm font-medium px-2 py-1 rounded-lg ${trend > 0 ? 'text-green-600 bg-green-50' : 'text-red-600 bg-red-50'}`}>
                        <TrendingUp size={16} />
                        <span>{trend > 0 ? '+' : ''}{trend}% vs last month</span>
                    </div>
                )}
            </div>

            <div className="h-[300px] w-full">
                <ResponsiveContainer width="100%" height="100%">
                    <AreaChart
                        data={chartData}
                        margin={{
                            top: 10,
                            right: 10,
                            left: 0,
                            bottom: 0,
                        }}
                    >
                        <defs>
                            <linearGradient id="colorRevenue" x1="0" y1="0" x2="0" y2="1">
                                <stop offset="5%" stopColor="#16a34a" stopOpacity={0.2} />
                                <stop offset="95%" stopColor="#16a34a" stopOpacity={0} />
                            </linearGradient>
                        </defs>
                        <CartesianGrid vertical={false} strokeDasharray="3 3" stroke="#f0f0f0" />
                        <XAxis
                            dataKey="month"
                            tickLine={false}
                            axisLine={false}
                            tickMargin={8}
                            fontSize={12}
                            tickFormatter={(value) => value}
                            stroke="#9ca3af"
                        />
                        <Tooltip
                            contentStyle={{ borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }}
                            formatter={(value: number | undefined) => [`$${value?.toLocaleString() ?? 0}`, 'Revenue']}
                        />
                        
                        <Area
                            type="monotone"
                            dataKey="revenue"
                            stroke="#16a34a"
                            strokeWidth={3}
                            fillOpacity={1}
                            fill="url(#colorRevenue)"
                        />
                    </AreaChart>
                </ResponsiveContainer>
            </div>
        </div>
    )
}
