/**
 * Generic OAuth Provider Interface
 * 
 * Every social media platform must implement this interface.
 * Adding a new platform = creating a new file in /providers that satisfies this contract.
 */

export interface OAuthTokens {
    accessToken: string;
    refreshToken?: string;
    expiresAt?: Date;
    scope?: string;
}

export interface OAuthProfile {
    providerAccountId: string;
    accountName: string;     // e.g. "@narrativee"
    avatarUrl?: string;
}

export interface OAuthProvider {
    /** Unique platform identifier, e.g. 'x', 'linkedin', 'instagram' */
    readonly platform: string;

    /** Human-readable name for UI, e.g. 'X (Twitter)' */
    readonly displayName: string;

    /** Required scopes for publishing */
    readonly scopes: string[];

    /**
     * Build the authorization URL that the user's browser is redirected to.
     * @param state - CSRF token stored in session, must be verified on callback.
     * @param redirectUri - The callback URL registered in the platform's dev console.
     * @param codeVerifier - Optional PKCE code verifier generated by the router.
     */
    getAuthorizationUrl(state: string, redirectUri: string, codeVerifier?: string): string;

    /**
     * Exchange the authorization code from the callback for access/refresh tokens.
     * @param code - The code returned by the platform after user consent.
     * @param redirectUri - Must match the one used in getAuthorizationUrl.
     * @param codeVerifier - Optional PKCE code verifier generated by the router.
     */
    exchangeCodeForTokens(code: string, redirectUri: string, codeVerifier?: string): Promise<OAuthTokens>;

    /**
     * Fetch the authenticated user's profile from the platform API.
     * Used to populate accountName and avatarUrl in the channels table.
     */
    fetchProfile(accessToken: string): Promise<OAuthProfile>;

    /**
     * Refresh an expired access token using the refresh token.
     * Returns null if the platform doesn't support refresh (user must re-auth).
     */
    refreshAccessToken?(refreshToken: string): Promise<OAuthTokens | null>;
}
