import type { Metadata } from "next";
import localFont from "next/font/local";
import { Story_Script, Petrona } from 'next/font/google'

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});
const story = Story_Script({
  variable: "--font-story",
  weight: ["400"]
})
const petrona = Petrona({
  variable: "--font-petrona",
  weight: ["400"]
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${petrona.variable} ${story.variable}`}>
        {children}
      </body>
    </html>
  );
}
