export type JsonPrimitive = string | number | boolean | null;

export type JsonValue =
  | JsonPrimitive
  | readonly JsonValue[]
  | { readonly [key: string]: JsonValue };

export type JsonObject = { readonly [key: string]: JsonValue };

export type MutableJsonObject = { [key: string]: JsonValue };

export type DateRange = {
  readonly start: string;
  readonly end: string;
};

export type PlatformName =
  | "x"
  | "linkedin"
  | "tiktok"
  | "instagram"
  | "youtube"
  | "newsletter";

export type ContentAssetKind =
  | "short_post"
  | "thread"
  | "professional_post"
  | "short_video_script"
  | "reel_script"
  | "shorts_metadata"
  | "newsletter_snippet"
  | "carousel_outline"
  | "hook_variation"
  | "cta_variation";

/** Platforms that currently support structured carousel generation. */
export type CarouselTargetPlatform = "instagram" | "linkedin";

/** Semantic role for a carousel slide in the narrative flow. */
export type CarouselSlideRole = "hook" | "insight" | "proof" | "cta";

/** Structured content for a single carousel slide. */
export interface CarouselSlideSpec {
  readonly [key: string]: JsonValue;
  readonly index: number;
  readonly role: CarouselSlideRole;
  readonly headline: string;
  readonly body: string;
  readonly visualBrief: string;
}

/** Platform-agnostic carousel content generated by the repurposing agent. */
export interface CarouselSpec {
  readonly [key: string]: JsonValue;
  readonly title: string;
  readonly baseCaption: string;
  readonly slideCount: number;
  readonly targetPlatforms: readonly CarouselTargetPlatform[];
  readonly slides: readonly CarouselSlideSpec[];
}

export type GeneratedContentAsset = {
  readonly id: string;
  readonly platform: PlatformName;
  readonly kind: ContentAssetKind;
  readonly title?: string;
  readonly body: string;
  readonly sourceAgent: string;
  readonly metadata: JsonObject;
};

export type ScheduleItem = {
  readonly assetId: string;
  readonly platform: PlatformName;
  readonly scheduledFor: string;
  readonly timezone: string;
  readonly payloadId: string;
};
